// Pass 10: 14 Claude Code arena challenges for small-business automation.
// `tier`    — gates who can complete (free < starter < playbook < operator).
// `section` — visual grouping key (free / starter / playbook / operator / architect).
// `proofType` — always 'url'; submit a screenshot, GitHub link, or Loom.

export const ARENA_CHALLENGES = [
  // ── FREE TIER (3 challenges) ───────────────────────────────────────────────
  {
    id: 'auto-review-request',
    tier: 'free',
    section: 'free',
    proofType: 'url',
    title: 'Auto Review Request',
    description: 'Build a script that generates personalized review request emails for recent clients — no more blank-page awkwardness.',
    difficulty: 'Easy',
    xp: 15,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code and describe your business and the service you just delivered.',
      'Prompt: "Write a Python script that takes a client name and service description and outputs a short, warm review request email with a direct ask."',
      'Run the script. Verify the tone matches your voice.',
      'Iterate: ask Claude Code to add a Google Reviews version and a LinkedIn recommendation version.',
      'Save as review_request.py. Next time a job closes, run it, copy, send.',
    ],
  },
  {
    id: 'appointment-reminder',
    tier: 'free',
    section: 'free',
    proofType: 'url',
    title: 'Appointment Reminder Builder',
    description: 'Stop manually writing reminder messages. Build a tool that drafts SMS and email reminders from your calendar details.',
    difficulty: 'Easy',
    xp: 20,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Paste in a sample appointment: client name, date, time, location or link.',
      'Prompt: "Write a Python script that takes appointment details and outputs both an SMS reminder (under 160 chars) and an email reminder."',
      'Test it with three different appointment types.',
      'Ask Claude Code to add a 24-hour version and a 1-hour version.',
      'Save as reminder_builder.py. Use it before every client call.',
    ],
  },
  {
    id: 'new-lead-auto-response',
    tier: 'free',
    section: 'free',
    proofType: 'url',
    title: 'New Lead Auto-Response',
    description: 'The first reply to a new lead sets the tone. Build a script that generates a personalized first-touch response in seconds.',
    difficulty: 'Easy',
    xp: 25,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Describe your typical lead — what they fill out in your form or how they reach out.',
      'Prompt: "Write a Python script that reads a lead\'s name, company, and stated problem, then outputs a first-touch response email that acknowledges their pain and proposes a call."',
      'Test with 3 different lead scenarios.',
      'Ask Claude Code to add a version for leads that mention budget and one for leads that don\'t.',
      'Save as lead_response.py. A sub-5-minute response beats 95% of your competitors.',
    ],
  },

  // ── STARTER TIER (3 challenges) ───────────────────────────────────────────
  {
    id: 'follow-up-sequence',
    tier: 'starter',
    section: 'starter',
    proofType: 'url',
    title: 'Follow-Up Sequence Generator',
    description: 'Never let a hot lead go cold. Build a 3-email follow-up sequence generator for any proposal you send.',
    difficulty: 'Easy',
    xp: 25,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Paste in a sample proposal or service description.',
      'Prompt: "Write a Python script that takes a proposal summary and generates a 3-part follow-up sequence: Day 2 check-in, Day 5 value-add, Day 10 final ask."',
      'Verify each email escalates appropriately without being pushy.',
      'Ask Claude Code to add subject line variations for each email.',
      'Save as followup_sequence.py. Run it the same day you send any proposal.',
    ],
  },
  {
    id: 'auto-invoice-generator',
    tier: 'starter',
    section: 'starter',
    proofType: 'url',
    title: 'Invoice Generator',
    description: 'Build a script that takes job details and outputs a formatted invoice — line items, rate, total, payment terms.',
    difficulty: 'Medium',
    xp: 35,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Describe your billing structure: hourly, project-based, or retainer.',
      'Prompt: "Write a Python script that takes client name, services rendered, hours or units, and rate, then outputs a formatted invoice as plain text or HTML."',
      'Test with a real client scenario.',
      'Ask Claude Code to add tax calculation and a net-30 payment terms section.',
      'Ask Claude Code to add a CSV export so you can track revenue over time.',
      'Save as invoice_generator.py.',
    ],
  },
  {
    id: 'payment-reminder',
    tier: 'starter',
    section: 'starter',
    proofType: 'url',
    title: 'Payment Reminder Escalator',
    description: 'Three tones — friendly, firm, final. Build them once, use them every time an invoice goes overdue.',
    difficulty: 'Medium',
    xp: 40,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Define your overdue scenario: invoice amount, due date, days overdue.',
      'Prompt: "Write a Python script that takes invoice details and days overdue, then outputs three reminder emails: Day 7 (friendly), Day 14 (firm), Day 30 (final notice with late fee warning)."',
      'Test each tier. Verify the language escalates correctly.',
      'Ask Claude Code to add a version that references the specific service delivered.',
      'Save as payment_reminder.py. Run it every Friday when you review outstanding invoices.',
    ],
  },

  // ── PLAYBOOK TIER (3 challenges) ──────────────────────────────────────────
  {
    id: 'client-onboarding-sequence',
    tier: 'playbook',
    section: 'playbook',
    proofType: 'url',
    title: 'Client Onboarding Sequence',
    description: 'A new client signs. Build the automation that handles the first 5 days — so you focus on delivery, not admin.',
    difficulty: 'Medium',
    xp: 40,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Map your current onboarding: every email, doc, and question in your process.',
      'Prompt: "Write a Python script that generates a 5-email onboarding sequence: welcome, next steps, resource delivery, check-in, and kickoff confirmation."',
      'Customize the output for your specific service type.',
      'Ask Claude Code to add a kickoff meeting agenda generator as a bonus output.',
      'Save as onboarding_sequence.py. Run it the moment a new contract is signed.',
    ],
  },
  {
    id: 'weekly-sales-report',
    tier: 'playbook',
    section: 'playbook',
    proofType: 'url',
    title: 'Weekly Sales Report Generator',
    description: 'Turn your raw activity log into a structured sales report for yourself or your team — in 3 minutes.',
    difficulty: 'Medium',
    xp: 50,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Describe what you track each week: leads contacted, calls booked, proposals sent, revenue closed.',
      'Prompt: "Write a Python script that takes weekly sales activity as input and outputs a structured report with Wins, Pipeline, and Next Week priorities."',
      'Test it with last week\'s actual numbers.',
      'Ask Claude Code to add a conversion rate calculator: leads → calls → proposals → closes.',
      'Save as weekly_sales_report.py. Run every Friday afternoon.',
    ],
  },
  {
    id: 'review-monitor-response',
    tier: 'playbook',
    section: 'playbook',
    proofType: 'url',
    title: 'Review Response Generator',
    description: 'Build a tool that generates on-brand responses to customer reviews — positive, neutral, and negative — in one pass.',
    difficulty: 'Hard',
    xp: 60,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Pull 3 real reviews you\'ve received: one 5-star, one 3-star, one 1-star.',
      'Prompt: "Write a Python script that reads a review and its star rating, then generates an appropriate response: positive (warm acknowledgment), neutral (thanks + improvement promise), negative (de-escalation + resolution offer)."',
      'Test with all 3 review types. Verify tone shifts correctly.',
      'Ask Claude Code to add a platform parameter for tone variation: Google vs. Yelp vs. LinkedIn.',
      'Save as review_responder.py. Target every review responded to within 24 hours.',
    ],
  },

  // ── OPERATOR TIER (3 challenges) ──────────────────────────────────────────
  {
    id: 'calendar-booking-crm',
    tier: 'operator',
    section: 'operator',
    proofType: 'url',
    title: 'Booking-to-CRM Bridge',
    description: 'Build a script that turns a booking confirmation email into a structured CRM contact entry — zero manual data entry.',
    difficulty: 'Hard',
    xp: 60,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Paste a sample booking confirmation email (Calendly, Cal.com, or any scheduler).',
      'Prompt: "Write a Python script that parses a booking confirmation email and extracts: name, email, phone, booked service, meeting time, and any notes. Output as JSON."',
      'Test with 3 different booking email formats.',
      'Ask Claude Code to generate a CSV export formatted for import into your CRM (HubSpot, Airtable, Notion, etc.).',
      'Save as booking_to_crm.py. Run it for every new booking confirmation you receive.',
    ],
  },
  {
    id: 'inbox-triage-agent',
    tier: 'operator',
    section: 'operator',
    proofType: 'url',
    title: 'Inbox Triage Agent',
    description: 'Build an agent that reads your emails and outputs a prioritized action list — urgent, reply needed, FYI, archive.',
    difficulty: 'Hard',
    xp: 75,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Paste 10 real emails from your inbox (anonymized if needed).',
      'Prompt: "Write a Python script that reads a batch of email subjects and bodies, then classifies each as: Urgent (same-day), Reply Needed (within 48h), FYI (no action), or Archive. Output a sorted action list."',
      'Test with your actual email mix.',
      'Ask Claude Code to add a draft reply for every Urgent and Reply Needed email.',
      'Ask Claude Code to add a 3-sentence inbox summary at the top.',
      'Save as inbox_triage.py. Run it every morning before touching your inbox.',
    ],
  },
  {
    id: 'meeting-notes-action-items',
    tier: 'operator',
    section: 'operator',
    proofType: 'url',
    title: 'Meeting Notes Processor',
    description: 'Paste raw notes in; get a clean summary, assigned action items, and a ready-to-send follow-up email — all in one run.',
    difficulty: 'Hard',
    xp: 80,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Paste in raw, unformatted notes from a real meeting.',
      'Prompt: "Write a Python script that takes raw meeting notes and outputs: 1) a 3-bullet executive summary, 2) an action item table with owner and deadline, 3) a follow-up email ready to send."',
      'Test with notes from your last three meetings.',
      'Ask Claude Code to add a "decisions made" section.',
      'Ask Claude Code to add a Markdown export option for Notion or Confluence.',
      'Save as meeting_processor.py. Run it within 15 minutes of every meeting ending.',
    ],
  },

  // ── AUTOMATION ARCHITECT BUILDS (2 capstone challenges) ───────────────────
  {
    id: 'full-client-onboarding-system',
    tier: 'operator',
    section: 'architect',
    proofType: 'url',
    title: 'Full Client Onboarding System',
    description: 'Build a complete onboarding pipeline: intake parsing, welcome email, contract checklist, kickoff agenda, and Day 1 task list — triggered from a single client record.',
    difficulty: 'Expert',
    xp: 100,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Map your full onboarding from first payment to first deliverable. List every step.',
      'Prompt: "Build a Python system that takes a new client record (name, service, start date, goals) and generates: intake summary, welcome email, contract checklist, 30-min kickoff agenda, and Day 1 task list."',
      'Wire each output to save to a folder named after the client.',
      'Test with 2 realistic client scenarios.',
      'Ask Claude Code to add a client-facing version (what they do) and an internal version (what you do).',
      'Run your next real client through the full system before Day 1. Document how long setup takes vs. your old process.',
    ],
  },
  {
    id: 'ai-customer-support-agent',
    tier: 'operator',
    section: 'architect',
    proofType: 'url',
    title: 'AI Customer Support Agent',
    description: 'Build a Claude-powered support agent that reads incoming questions and generates accurate, on-brand responses from your own knowledge base.',
    difficulty: 'Expert',
    xp: 150,
    tools: ['Claude Code'],
    steps: [
      'Open Claude Code. Write a FAQ document with your 20 most common client questions and your exact answers.',
      'Prompt: "Build a Python script that takes a customer question and a FAQ document, then generates an accurate, on-brand support response using only the information in the FAQ."',
      'Test with 10 question variations — including edge cases not directly in your FAQ.',
      'Ask Claude Code to add a confidence score: HIGH (directly answered), MEDIUM (inferred), ESCALATE (not in FAQ).',
      'Ask Claude Code to add logging that tracks which questions most often trigger ESCALATE — those are your FAQ gaps.',
      'Run it for one week on real incoming support questions. Document the time saved per day.',
    ],
  },
]
