// Pass 9: Arena challenge catalog.
// `tier` gates who can complete (uses existing tier hierarchy free<starter<playbook<operator).
// `proofType` determines the submission field: 'text' = describe it, 'url' = paste a link.

export const ARENA_CHALLENGES = [
  // ── FREE TIER (3 challenges, 15–25 XP) ────────────────────────────────────
  {
    id: 'follow-up-machine',
    tier: 'free',
    proofType: 'text',
    title: 'Auto Follow-Up Machine',
    description: 'Stop rewriting the same follow-up from scratch. Build a reusable template system for post-meeting, no-reply, and after-intro emails.',
    difficulty: 'Easy',
    xp: 20,
    tools: ['Gmail', 'ChatGPT'],
    steps: [
      'Identify your 3 most common follow-up scenarios — post-meeting, no-reply nudge, after intro.',
      'In ChatGPT, write a prompt template for each: include slots for context, recipient role, and desired next step.',
      'Save the three prompts in a single doc labeled "Follow-Up Library."',
      'Next time you need a follow-up: paste notes + role into the right template, run, paste into Gmail draft.',
      'Tweak tone, send. You just cut 10 minutes to 60 seconds.',
    ],
  },
  {
    id: 'review-request-engine',
    tier: 'free',
    proofType: 'text',
    title: 'Review Request Engine',
    description: 'Ask every client for a review without forgetting any of them. Warm, short, and repeatable.',
    difficulty: 'Easy',
    xp: 15,
    tools: ['Gmail', 'ChatGPT', 'Spreadsheet'],
    steps: [
      'Pull a list of clients from the last 30 days who you haven\'t asked for a review.',
      'Write a prompt: "Write a warm review request email for [client] who purchased [service]. Under 80 words, one clear ask."',
      'Run the template per client. Paste output into Gmail.',
      'Log each ask in a tracking sheet so no one gets double-asked.',
    ],
  },
  {
    id: 'content-repurposer',
    tier: 'free',
    proofType: 'text',
    title: 'Content Repurposer',
    description: 'One blog post, five assets. Stop creating from zero every time you need to post.',
    difficulty: 'Medium',
    xp: 25,
    tools: ['ChatGPT'],
    steps: [
      'Pick one existing blog post, essay, or long-form piece you\'ve published.',
      'Prompt ChatGPT: "Turn this post into 1 LinkedIn post, 3 tweets, 1 newsletter blurb, 1 Instagram caption, 1 YouTube description. Keep my voice."',
      'Review outputs — rewrite anything that doesn\'t sound like you.',
      'Schedule the five pieces across 5 days.',
    ],
  },

  // ── STARTER TIER (5 new, 25–50 XP) ────────────────────────────────────────
  {
    id: 'invoice-autopilot',
    tier: 'starter',
    proofType: 'url',
    title: 'Invoice on Autopilot',
    description: 'Draft invoices and payment reminders with one prompt. No more chasing overdue amounts from scratch.',
    difficulty: 'Easy',
    xp: 30,
    tools: ['ChatGPT', 'Gmail', 'Invoicing tool'],
    steps: [
      'Template 1: "Generate an invoice for [client] for [service] at [price]. Include payment terms net 30. Professional tone."',
      'Template 2: "Write a payment reminder for [client], [X days] overdue, amount $[Y]. Firm but polite."',
      'Run template 1 for any open invoice; paste into your invoicing tool.',
      'Run template 2 for anything overdue; paste into Gmail.',
    ],
  },
  {
    id: 'lead-capture-crm',
    tier: 'starter',
    proofType: 'url',
    title: 'Lead Capture to CRM',
    description: 'Form submissions → enriched leads → CRM contacts. Zero manual entry.',
    difficulty: 'Medium',
    xp: 40,
    tools: ['Zapier', 'Google Forms', 'CRM (Airtable/HubSpot/Notion)'],
    steps: [
      'Build a Google Form with fields: name, email, company, pain point.',
      'In Zapier, trigger = New Google Forms Response.',
      'Add a Formatter step to extract the domain from the email.',
      'Add an action: create contact in your CRM with all fields mapped.',
      'Submit a test entry. Verify it lands in the CRM with the domain field populated.',
    ],
  },
  {
    id: 'meeting-prep-brief',
    tier: 'starter',
    proofType: 'url',
    title: 'Meeting Prep Brief',
    description: 'Walk into every client call with a one-pager. Three minutes of prep, better outcomes.',
    difficulty: 'Easy',
    xp: 25,
    tools: ['ChatGPT', 'Calendar'],
    steps: [
      '30 minutes before a meeting, paste attendee names, company, and any prior email thread into ChatGPT.',
      'Prompt: "Build a meeting brief — their likely goals, 3 questions I should ask, 2 risks to watch for."',
      'Review, trim, paste into the calendar event notes so it\'s there when the call starts.',
    ],
  },
  {
    id: 'weekly-report-generator',
    tier: 'starter',
    proofType: 'url',
    title: 'Weekly Report Generator',
    description: 'Turn end-of-week bullet notes into a stakeholder-ready report in three minutes.',
    difficulty: 'Medium',
    xp: 35,
    tools: ['ChatGPT', 'Notes app'],
    steps: [
      'Each Friday, dump raw bullet notes of what you did this week into a single doc.',
      'Prompt: "Turn these bullets into a 3-section weekly report — Wins, Blockers, Next Week. Crisp, stakeholder-ready."',
      'Add any missing metrics or numbers — AI won\'t invent those for you.',
      'Send.',
    ],
  },
  {
    id: 'complaint-router',
    tier: 'starter',
    proofType: 'url',
    title: 'Complaint Router',
    description: 'Auto-classify incoming customer complaints and route each one to the right place.',
    difficulty: 'Hard',
    xp: 50,
    tools: ['Gmail', 'Zapier', 'ChatGPT', 'Slack'],
    steps: [
      'Add a Gmail label "support" and filter incoming support emails to it.',
      'Zap trigger: new email with label "support."',
      'ChatGPT step: classify body as billing / technical / refund / other.',
      'Router: post to the matching Slack channel (or create a ticket in your tracker).',
      'Test with 3 sample emails. Check each lands in the right channel.',
    ],
  },

  // ── PLAYBOOK TIER (3 new, 50–75 XP) ───────────────────────────────────────
  {
    id: 'onboarding-sequence',
    tier: 'playbook',
    proofType: 'url',
    title: 'Onboarding Sequence',
    description: 'Five-email sequence that takes a new client from signed to shipping in 30 days — with no manual sends from you.',
    difficulty: 'Medium',
    xp: 50,
    tools: ['ChatGPT', 'Email tool (Mailchimp/ConvertKit/etc)'],
    steps: [
      'Map the 5 milestones a new client hits in their first 30 days.',
      'For each milestone, prompt ChatGPT to write an email: warm, helpful, one CTA.',
      'Load all 5 into your email tool with time-delay triggers.',
      'Wire the sequence to fire when a new client is added to your CRM.',
      'Send yourself a test by creating a dummy client. Check all 5 arrive on schedule.',
    ],
  },
  {
    id: 'ai-proposal-builder',
    tier: 'playbook',
    proofType: 'url',
    title: 'AI Proposal Builder',
    description: 'Turn a 30-minute discovery call into a delivered proposal in under an hour.',
    difficulty: 'Hard',
    xp: 65,
    tools: ['ChatGPT', 'Proposal template (Google Doc/Notion)'],
    steps: [
      'After a discovery call, paste notes + stated goals + your service options into ChatGPT.',
      'Prompt: "Draft a 2-page proposal — problem summary, proposed solution, timeline, investment. Include tier 1 / tier 2 / VIP options."',
      'Pour the output into your proposal template and format.',
      'Send within 24 hours of the call. Speed wins.',
    ],
  },
  {
    id: 'hiring-pipeline',
    tier: 'playbook',
    proofType: 'url',
    title: 'Hiring Pipeline',
    description: 'End-to-end AI-assisted hiring — JD, resume scoring, interview questions, hiring decision.',
    difficulty: 'Hard',
    xp: 75,
    tools: ['ChatGPT', 'Spreadsheet or ATS'],
    steps: [
      'Prompt 1: "Generate a JD for a [role] who will [one-line job]. 5 must-haves, 3 nice-to-haves."',
      'Prompt 2: "Score these 10 resumes against the JD on 5 criteria. Rank them. Output a shortlist of 3."',
      'Prompt 3: "Generate 8 interview questions tailored to each top-3 candidate\'s background."',
      'After interviews, prompt 4: "Here are my notes on each candidate. Summarize into a hire/no-hire recommendation with reasoning."',
    ],
  },

  // ── OPERATOR TIER (1 new, capstone) ───────────────────────────────────────
  {
    id: 'full-client-ops',
    tier: 'operator',
    proofType: 'url',
    title: 'Full Client Ops System',
    description: 'Capstone. Stitch 5+ workflows into a single running business ops system. One client cascades end-to-end.',
    difficulty: 'Expert',
    xp: 150,
    tools: ['Zapier', 'CRM', 'ChatGPT', 'Gmail', 'Slack'],
    steps: [
      'Map your full client lifecycle: intake → proposal → kickoff → delivery → invoice → retention.',
      'Build at least one automation at each stage (lead capture, proposal generator, onboarding sequence, status reports, invoice reminders, review requests).',
      'Connect them via Zapier or Make so a single event cascades through the chain.',
      'Run your next real client through the full system end-to-end. Do not intervene manually.',
      'Measure: how much time did this save vs the same client handled manually? Document the number.',
    ],
  },
]
